name: Deploy to private repo

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, edited, synchronize]


jobs:
  checkout_and_proto_copy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3.0.0
      with:
        ref: master
        repository: matwey-s/serverless-telegram-bot
        path: serverless-telegram-bot
        
    - name: Checkout destination repository
      uses: actions/checkout@v3.0.0     
      with:
        ref: master
        repository: matwey-s/matwey-s
        path: matwey-s
        token: ${{ secrets.TOKEN }}        
        
    - name: Copy Proto Files
      run: |
        ls -la
        ls -la serverless-telegram-bot
        cp -r serverless-telegram-bot/serverless.yml matwey-s/folder
        git -C matwey-s add folder
        ls -a matwey-s/folder
        
    - name: Delete src/codegen and types
      run: |
        rm -rf matwey-s/folder/file2
        git -C matwey-s rm -rf folder/file2
        
    - name: Determine npm version
      run: |
          if [[ "${{ github.event.pull_request.title }}" == *"major"* ]]; then
            echo "::set-env name=NPM_VERSION::major"
          elif [[ "${{ github.event.pull_request.title }}" == *"minor"* ]]; then
            echo "::set-env name=NPM_VERSION::minor"
          elif [[ "${{ github.event.pull_request.title }}" == *"patch"* ]]; then
            echo "::set-env name=NPM_VERSION::patch"
          fi

    - name: Bump npm version
      run: |
          if [ "${{ env.NPM_VERSION }}" == "major" ]; then
            npm version major
          elif [ "${{ env.NPM_VERSION }}" == "minor" ]; then
            npm version minor
          elif [ "${{ env.NPM_VERSION }}" == "patch" ]; then
            npm version patch
          fi

        
#     - name: Publish NPM Package
#       run: npm publish --access public --prefix matwey-s
      
    - name: Commit files & push
      run: |
        git -C matwey-s config   user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git -C matwey-s config   user.name "github-actions[bot]"
        git -C matwey-s commit  -a -m "Add changes"
        git -C matwey-s push
